name: athnatcount
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10
  - pip
  - pandas>=2.0
  - requests>=2.31
  - r-base>=4.3
  - r-seurat
  - r-matrix
  - r-dplyr
  - r-ggplot2
  - r-patchwork
  - r-readr
  - r-progress
  - r-tidyr
  - r-stringr
  - r-rcolorbrewer
  - r-gridextra
  - r-scales
  - r-viridis
  - r-ggrepel
  - r-corrplot
  - r-pheatmap
  - r-venndiagram
  - bioconductor-rtracklayer
  - bioconductor-genomicranges
  - r-pbapply